lib: [
  "_build/install/default/lib/ligo-types/META"
  "_build/install/default/lib/ligo-types/dune-package"
  "_build/install/default/lib/ligo-types/mini_c_types/PP.ml" {"mini_c_types/PP.ml"}
  "_build/install/default/lib/ligo-types/mini_c_types/PP.mli" {"mini_c_types/PP.mli"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types.a" {"mini_c_types/mini_c_types.a"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types.cma" {"mini_c_types/mini_c_types.cma"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types.cmi" {"mini_c_types/mini_c_types.cmi"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types.cmt" {"mini_c_types/mini_c_types.cmt"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types.cmx" {"mini_c_types/mini_c_types.cmx"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types.cmxa" {"mini_c_types/mini_c_types.cmxa"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types.ml" {"mini_c_types/mini_c_types.ml"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types__PP.cmi" {"mini_c_types/mini_c_types__PP.cmi"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types__PP.cmt" {"mini_c_types/mini_c_types__PP.cmt"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types__PP.cmti" {"mini_c_types/mini_c_types__PP.cmti"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types__PP.cmx" {"mini_c_types/mini_c_types__PP.cmx"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types__Types.cmi" {"mini_c_types/mini_c_types__Types.cmi"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types__Types.cmt" {"mini_c_types/mini_c_types__Types.cmt"}
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types__Types.cmx" {"mini_c_types/mini_c_types__Types.cmx"}
  "_build/install/default/lib/ligo-types/mini_c_types/types.ml" {"mini_c_types/types.ml"}
  "_build/install/default/lib/ligo-types/opam"
  "_build/install/default/lib/ligo-types/stage_common_types/PP.ml" {"stage_common_types/PP.ml"}
  "_build/install/default/lib/ligo-types/stage_common_types/PP_enums.ml" {"stage_common_types/PP_enums.ml"}
  "_build/install/default/lib/ligo-types/stage_common_types/enums.ml" {"stage_common_types/enums.ml"}
  "_build/install/default/lib/ligo-types/stage_common_types/helpers.ml" {"stage_common_types/helpers.ml"}
  "_build/install/default/lib/ligo-types/stage_common_types/helpers.mli" {"stage_common_types/helpers.mli"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types.a" {"stage_common_types/stage_common_types.a"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types.cma" {"stage_common_types/stage_common_types.cma"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types.cmi" {"stage_common_types/stage_common_types.cmi"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types.cmt" {"stage_common_types/stage_common_types.cmt"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types.cmx" {"stage_common_types/stage_common_types.cmx"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types.cmxa" {"stage_common_types/stage_common_types.cmxa"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types.ml" {"stage_common_types/stage_common_types.ml"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__Enums.cmi" {"stage_common_types/stage_common_types__Enums.cmi"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__Enums.cmt" {"stage_common_types/stage_common_types__Enums.cmt"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__Enums.cmx" {"stage_common_types/stage_common_types__Enums.cmx"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__Helpers.cmi" {"stage_common_types/stage_common_types__Helpers.cmi"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__Helpers.cmt" {"stage_common_types/stage_common_types__Helpers.cmt"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__Helpers.cmti" {"stage_common_types/stage_common_types__Helpers.cmti"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__Helpers.cmx" {"stage_common_types/stage_common_types__Helpers.cmx"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__PP.cmi" {"stage_common_types/stage_common_types__PP.cmi"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__PP.cmt" {"stage_common_types/stage_common_types__PP.cmt"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__PP.cmx" {"stage_common_types/stage_common_types__PP.cmx"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__PP_enums.cmi" {"stage_common_types/stage_common_types__PP_enums.cmi"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__PP_enums.cmt" {"stage_common_types/stage_common_types__PP_enums.cmt"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__PP_enums.cmx" {"stage_common_types/stage_common_types__PP_enums.cmx"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__Types.cmi" {"stage_common_types/stage_common_types__Types.cmi"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__Types.cmt" {"stage_common_types/stage_common_types__Types.cmt"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types__Types.cmx" {"stage_common_types/stage_common_types__Types.cmx"}
  "_build/install/default/lib/ligo-types/stage_common_types/types.ml" {"stage_common_types/types.ml"}
]
libexec: [
  "_build/install/default/lib/ligo-types/mini_c_types/mini_c_types.cmxs" {"mini_c_types/mini_c_types.cmxs"}
  "_build/install/default/lib/ligo-types/stage_common_types/stage_common_types.cmxs" {"stage_common_types/stage_common_types.cmxs"}
]
doc: [
  "_build/install/default/doc/ligo-types/LICENSE.md"
]
